### PR TITLE
JSON API Migration and Support the Arrange.Space frontend JSON

### PR DESCRIPTION
**Pull request by Jeffchiucp**
* Fix the bug with Arrange.Space in #6 
* modified domain to fix the issue

### CODE REVIEW

**Comment by Jeffchiucp** [comment]
Screen Shot 2019-10-19 at 12 19 30 PM
working with the both json file : https://pastebin.com/raw/JkyhTwD1

**Review by deonjo — APPROVED** [review]
LGTM

**Comment by Jeffchiucp** [comment]
@deonjo  Is there any JSON file with different _id that you want me to test it out on the backend?

**Comment by deonjo** [comment]
Yes, you can create a JSON by using the current FE, to make an arrangement,
and then catching the network packet and using that.


On October 21, 2019 at 2:26:03 PM, Jeff Chiu (notifications@github.com)
wrote:

@deonjo <https://github.com/deonjo> Is there any JSON file with different
_id that you want me to test it out on the backend?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arrangement-io/arrange-space-spring/pull/7?email_source=notifications&email_token=AADQYMWFDP52FXQMANJEGS3QPYM6VA5CNFSM4JCWLTF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB33AVQ#issuecomment-544714838>,
or unsubscribe

**Comment by jeff20009** [comment]
I am going to connect the BE and FE today using my Gmail, trying to do it locally it right now, and testing it out if the backend supports the current FE.

**Comment by deonjo** [comment]
ok sounds good

**Comment by Jeffchiucp** [comment]
thanks for the code review, but I was able to test out with multiple JSON objects for arrangement POST API

**Pull request merged**
